import json
import os

def load_scan_results(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def group_by_plugin(results):
    grouped = {}
    for filepath, vulns in results.items():
        parts = filepath.split(os.sep)
        try:
            plugin = parts[1]  # plugins-wp/{plugin}/...
        except IndexError:
            plugin = "Unknown"
        grouped.setdefault(plugin, {})[filepath] = vulns
    return grouped

def generate_html(grouped_results, output_path):
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PHP Plugin Vulnerability Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f6f8fa;
            margin: 20px;
            color: #333;
        }}
        h1 {{
            color: #1a73e8;
        }}
        h2 {{
            border-bottom: 2px solid #ccc;
            padding-bottom: 5px;
            margin-top: 40px;
        }}
        .file-block {{
            margin-bottom: 20px;
            padding: 10px;
            border-left: 4px solid #1a73e8;
            background: #fff;
            box-shadow: 0 0 5px rgba(0,0,0,0.05);
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 8px;
            font-size: 14px;
        }}
        th {{
            background-color: #f2f2f2;
            text-align: left;
        }}
        .vuln-type {{
            font-weight: bold;
            color: #d93025;
        }}
        .footer {{
            margin-top: 50px;
            font-size: 12px;
            text-align: center;
            color: #999;
        }}
    </style>
</head>
<body>
    <h1>PHP Plugin Vulnerability Report</h1>
""")
            for plugin, files in grouped_results.items():
                f.write(f'<h2>Plugin: {plugin}</h2>\n')
                for filepath, vulns in files.items():
                    f.write(f'<div class="file-block">\n')
                    f.write(f'<h3>{filepath}</h3>\n')
                    for vuln_type, vuln_list in vulns.items():
                        f.write(f'<p class="vuln-type">{vuln_type} ({len(vuln_list)} issues)</p>\n')
                        f.write('<table>\n<tr><th>Line</th><th>Code</th></tr>\n')
                        for line_num, code in vuln_list:
                            code_html = code.replace('<', '&lt;').replace('>', '&gt;')
                            f.write(f'<tr><td>{line_num}</td><td><code>{code_html}</code></td></tr>\n')
                        f.write('</table>\n')
                    f.write('</div>\n')

            f.write("""
    <div class="footer">
        Generated by PHP Vulnerability Scanner
    </div>
</body>
</html>
""")
        print("[+] Report successfully generated at report_by_plugin.html")
    except Exception as e:
        print(f"[-] Failed to generate report: {e}")

if __name__ == "__main__":
    results = load_scan_results("scan_result.json")
    grouped = group_by_plugin(results)
    generate_html(grouped, "vuln_report.html")
